# Generated by Django 3.0.5 on 2021-05-25 01:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('users', '0002_auto_20210521_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stocks',
            field=djongo.models.fields.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='stonks',
            field=models.ManyToManyField(to='stocks.Stock'),
        ),
    ]
