# Generated by Django 3.0.5 on 2021-05-25 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210525_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stocks',
        ),
    ]
