# Generated by Django 3.0.5 on 2021-05-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('users', '0006_auto_20210525_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stocks',
            field=models.ManyToManyField(to='stocks.Stock'),
        ),
    ]
