# Generated by Django 3.0.5 on 2021-05-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210525_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stockss',
            field=models.CharField(default='', max_length=200),
        ),
    ]
