# Generated by Django 3.0.5 on 2021-05-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_stockss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stocks',
        ),
    ]
